/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcumenAbi } from "./AcumenAbi";

export { AcumenAbi__factory } from "./factories/AcumenAbi__factory";
