import { useEffect, useState } from "react";
import { TAI64 } from "tai64";
import { Wallet, BN, bn } from "fuels";
import "./App.css";

// Import the contract factory from the folder generated by the fuelchain
// command
import  {AcumenAbi__factory} from "./contracts/factories/AcumenAbi__factory";

// The private key of the `owner` in chainConfig.json.
// This enables us to have an account with an initial balance.
const WALLET_SECRET =
  "2ef4b3f83de6d32c9e31c796e3175fc48eeb875d9824782d7b8d56db8a87ef2f";

// The ID of the contract deployed to our local node.
// The contract ID is displayed when the `forc deploy` command is run.
// E.g. Contract id: 0xa326e3472fd4abc417ba43e369f59ea44f8325d42ba6cf71ec4b58123fd8668a
// const CONTRACT_ID = "0xa326e3472fd4abc417ba43e369f59ea44f8325d42ba6cf71ec4b58123fd8668a"
const CONTRACT_ID =
  "0xc25a3d8ec5369db57961764acb65cb9040938f0c0ff6494d3947ac822ac4adb1";

// Create a "Wallet" using the private key above.
const wallet1 = Wallet.fromPrivateKey(
  WALLET_SECRET,
  "https://node-beta-2.fuel.network/graphql"
);

// Connect a "Contract" instance using the ID of the deployed contract and the
// wallet above.

const contract = AcumenAbi__factory.connect(CONTRACT_ID, wallet1);
const address =
  "0x0000000000000000000000000000000000000000000000000000000000000000";

function App() {
  const checkBal = async () => {
    console.log(
     
        contract.id

    );
  };
  // useEffect(() => {
  //   async function main() {
  //     // Executes the `counter()` function to query the current contract state.
  //     // the `.get()` method is read-only. Therefore, doesn't spend coins.
  //     const { value } = await contract.functions.deposit();
  //     setCounter(Number(value));
  //   }
  //   main();
  // }, []);

  async function deposit(e: any) {
    e.preventDefault();
    const data = new FormData(e.target);
    const deposit = await contract.functions
      .deposit(bn(String(data.get("PoolID"))), bn(String(data.get("Amount"))))
      .txParams({ gasPrice: 1 })
      .callParams({ forward: [bn(String(data.get("Amount"))), address] })
      .call();

    console.log("transaction", deposit);
  }

  async function withdraw(e:any) {
    e.preventDefault();
    const data = new FormData(e.target);
    const withdraw = await contract.functions.withdraw(bn(String(data.get("PoolID"))), bn(String(data.get("Amount"))))
    .txParams({ gasPrice: 1 })
    .call();

    console.log("withdraw", withdraw);
  }

  async function borrow(e:any) {
    e.preventDefault();
    const data = new FormData(e.target);
    const withdraw = await contract.functions.withdraw(bn(String(data.get("PoolID"))), bn(String(data.get("Amount"))))
    .txParams({ gasPrice: 1 })
    .call();

    console.log("withdraw", withdraw);
  }


  async function repay(e:any) {
    e.preventDefault();
    const data = new FormData(e.target);
    const withdraw = await contract.functions.withdraw(bn(String(data.get("PoolID"))), bn(String(data.get("Amount"))))
    .txParams({ gasPrice: 1 })
    .call();

    console.log("withdraw", withdraw);
  }

  async function createPool(e:any)  {
    e.preventDefault();
    const data = new FormData(e.target);
    let qrtPayout: boolean;
    let isStaking: boolean;

    if (data.get("qrtPayout") === "yes") {
      qrtPayout = true;
    } else {
      qrtPayout = false;
    }

    if (data.get("staking") === "yes") {
      isStaking = true;
    } else {
      isStaking = false;
    }



    // const date = new Date(String(data.get("startDate")));
    // const time = String(data.get("startTime"));
    // const timeSplit = time.split(":");
    // const hours = Number(timeSplit[0]);
    // const minutes = Number(timeSplit[1]);
    // const seconds = Number(timeSplit[2]);
    // const timestamp = date.getTime() / 1000 + hours * 3600 + minutes * 60 + seconds;
    // const timestampHex = timestamp.toString(16);
    // const timestampHexPadded = timestampHex.padStart(16, "0");
    // const timestampHexPaddedReversed = timestampHexPadded.match(/.{2}/g)?.reverse().join("");
    // const timestampHexPaddedReversedWithPrefix = "4000000000000000" + timestampHexPaddedReversed;
    // const timestampHexPaddedReversedWithPrefixBN = bn(timestampHexPaddedReversedWithPrefix);
   

    // 4611686020097040401

    // 4611686020097058000


    const poolId = await contract.functions
      .create_pool(
        isStaking,
        String(data.get("poolName")),
        new BN(Number(data.get("apy"))),
        qrtPayout,
        new BN(Number(data.get("duration"))),
        new BN(Number(data.get("startTime"))),
        new BN(Number(data.get("endTime"))),
        new BN(Number(data.get("maxUtilization"))),
        bn.parseUnits(String(data.get("capacity"))),
        new BN(Number(data.get("limitPerPerson")))
      )
      .txParams({ gasPrice: 1 })
      .call();

    console.log("Sent to the chain", poolId);
  }
  const [pools, setPools] = useState(0);

  async function allPools() {
    const { value } = await contract.functions.get_total_pools().get();
    console.log(Number(value));
    setPools(Number(value));
  }

  async function poolDetails() {
    const value1 = await contract.functions.get_pool_info_from_id(0).get();
    const { value } = value1;
    console.log(Number(value.funds.balance));
  }

  async function userDetails() {
    const value1 = await contract.functions.get_total_stakes_of_user(0).get();
   const {value} = value1;
    console.log(value1);
  }

  async function editPool(e:any) {
    e.preventDefault();
    let paused: boolean;
    const data = new FormData(e.target);
    if (data.get("paused") === "yes") {
      paused = true;
    } else {
      paused = false;
    }

    const apple = await contract.functions
      .edit_pool(
        Number(data.get("poolId")),
        String(data.get("poolName")),
        paused,
        new BN(Number(data.get("apy"))),
        new BN(Number(data.get("maxUtilization"))),
        new BN(Number(data.get("capacity")))
      )
      .txParams({ gasPrice: 1 })
      .call();
    console.log(apple);
  }

  useEffect(() => {
    const today: any = String(new Date())
    console.log(today)
   console.log(Number(TAI64.fromUnix(
   today / 1000)
  ))
    allPools();
    checkBal();
    poolDetails();
    //userDetails();
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <div className="App-items">
          <p>Deposit</p>
          <form onSubmit={deposit}>
            <input name="PoolID" className="" placeholder="PoolID"></input>
            <input
              name="Amount"
              className=""
              placeholder="Amount"
              step=".001"
            ></input>
            <button type="submit">Submit</button>
          </form>
        </div>

        <div className="App-items">
          <p>Withdraw</p>
          <form onSubmit={withdraw}>
          <input name="PoolID" className=""></input>
          <input name="Amount" className=""></input>
          <button type="submit">Submit</button>
          </form>
        </div>

        <div className="App-items">
          <p>Borrow</p>
          <form onSubmit={borrow}>
          <input name="PoolID" className=""></input>
          <input name="Amount" className=""></input>
          <button type="submit">Submit</button>
          </form>
        </div>

        <div className="App-items">
          <p>Repay</p>
          <input name="PoolID" className=""></input>
          <input name="Amount" className=""></input>
          <button type="submit">Submit</button>
        </div>

        <div className="App-items">
          <p>Create Pool: {pools}</p>
          <form onSubmit={createPool} className="Input">
            <p>Yes is Left, No is Right</p>
            <span>
              Staking?
              <input
                name="staking"
                value="yes"
                type="radio"
                className="App-inputs"
              ></input>{" "}
              <input
                name="staking"
                value="no"
                type="radio"
                className="App-inputs"
              ></input>
            </span>
            <input
              name="poolName"
              placeholder="Name"
              className="App-inputs"
            ></input>
            <input name="apy" placeholder="apy" className="App-inputs"></input>
            <span>
              qrtPayout
              <input
                name="qrtPayout"
                value="yes"
                type="radio"
                className="App-inputs"
              ></input>
              <input
                name="qrtPayout"
                value="no"
                type="radio"
                className="App-inputs"
              ></input>
            </span>
            <input
              name="duration"
              placeholder="duration"
              className="App-inputs"
            ></input>
           

<input       name="startTime"
              placeholder="startTime"
              className="App-inputs"
            ></input>

       
<input
              name="endTime"
              placeholder="endTime"
              className="App-inputs"
            ></input>

            <input
              name="maxUtilization"
              placeholder="Max Utilization"
              className="App-inputs"
            ></input>
            <input
              name="capacity"
              placeholder="capacity"
              className="App-inputs"
            ></input>
            <input
              name="limitPerPerson"
              placeholder="Limit Per Person"
              className="App-inputs"
            ></input>

            <button className="App-inputs" type="submit">
              Submit
            </button>
          </form>
        </div>

        <div className="App-items">
          <p>Edit Pool</p>
          <form onSubmit={editPool} className="Input">
            <input
              className="App-inputs"
              name="poolId"
              placeholder="pool_id"
            ></input>
            <input
              className="App-inputs"
              name="poolName"
              placeholder="pool_name"
            ></input>
            <span>
              paused
              <input
                name="paused"
                value="yes"
                type="radio"
                className="App-inputs"
              ></input>
              <input
                name="paused"
                value="no"
                type="radio"
                className="App-inputs"
              ></input>
            </span>
            <input className="App-inputs" name="apy" placeholder="apy"></input>
            <input
              className="App-inputs"
              name="maxUtilization"
              placeholder="max_utilization"
            ></input>
            <input
              className="App-inputs"
              name="capacity"
              placeholder="capacity"
            ></input>
            <button className="App-inputs" type="submit">
              Submit
            </button>
          </form>
        </div>
      </header>
    </div>
  );
}

export default App;




